name: Bug report
description: Create a report to help us improve
labels: ["bug"]
assignees: ["PapitaConPure"]
projects: ["PapitaConPure/6"]
body:
  - type: checkboxes
    id: searched-issues
    attributes:
      options:
        - label: I've searched existing issues and found nothing related to my issue.
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Describe the actions that led up to the bug.
      placeholder: Steps to reproduce the behavior
      value: |
        1. Go to ...
        2. Click on ...
        3. See the error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Anything else to know?
    validations:
      required: false
