name: Command request
description: Suggest a command for Bot de Puré
title: "p!command"
labels: ["commands"]
assignees: ["PapitaConPure"]
projects: ["PapitaConPure/6"]
body:
  - type: checkboxes
    id: searched-issues
    attributes:
      label: Is there an existing issue for this?
      description: Have you searched the existing issues for this command request?
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: names
    attributes:
      label: Command name and aliases
      description: |
        Specify the name and aliases you'd like this command to use. Separated by commas.
        Spanish, English and Japanese allowed.
      placeholder: comando, command, cmd, c
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Command description
      description: |
        Describe the behavior of the command, and any additional information that would be relevant to the user.
        Preferably, speaking from the perspective Bot de Puré (female). Spanish, English and Japanese allowed.
      placeholder: Makes me do something very silly
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Command options
      description: |
        Detail the options that shape the behavior command, in a way that the user can understand.
        Preferably, speaking from the perspective Bot de Puré (female). Spanish, English and Japanese allowed.
      placeholder: "* `option display` _(Option data type)_ option description"
      value: |
        * `<param>` _(Type)_ param description
        * `--flag` flag description
        * `--flag2 <f2>` _(Type)_ expressive flag description
    validations:
      required: false
