name: Feature request
about: Suggest an idea for this project
labels: ["enhancement"]
assignees: ["PapitaConPure"]
body:
  - type: checkboxes
    attributes:
      options:
        - label: I've searched existing issues and found nothing related to my issue.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: What's your desired solution?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: What else could be done?
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Type some extra information or drag and drop images here
    validations:
      required: false
